Bugfix/sns encrypt cmk
sourcefuse/terraform-aws-arc-security pull request #2
Opened 2023-11-17 18:29 UTC by hernanku

2023-11-17 19:15 UTC, jamescrowley321 approved these changes

2023-11-17 19:24 UTC, jamescrowley321 requested changes
Needs approval from @mayank0202 @tsaucier-sf @vijay-stephen

2023-11-20 17:03 UTC, tsaucier-sf commented on example/main.tf
> +  # source = "git::https://github.com/sourcefuse/terraform-aws-arc-security.git?ref=bugfix/sns-encrypt-cmk"
Remove this

2023-11-20 17:04 UTC, tsaucier-sf commented on locals.tf
> +    Id      = "key-policy-1",
We should let AWS auto-assign the Id, please omit.

2023-11-24 14:04 UTC, mayank0202 commented
THIS SHOULD BE CLOSED @jamescrowley321  @vijay-stephen  @hernanku

2023-11-24 14:04 UTC, closed without merging