Security module - being tested
sourcefuse/terraform-aws-arc-security pull request #3
Opened 2023-11-17 19:27 UTC by jamescrowley321

2023-11-20 13:39 UTC, hernanku commented on main.tf
Might be a good idea to make the `create_sns` into variables, and have a diff variable name for each of the module services 
`create_sns_topic  = true`  
`create_sns_topic  = var.create_security_hub_sns`

2023-11-20 13:42 UTC, hernanku commented on main.tf
The cloudposse modules have a variable called `enabled` which controls module creating resources.
We could explore that in lieu of count?
![image](https://github.com/sourcefuse/terraform-aws-arc-security/assets/43397610/76a15ec7-c623-4760-a8fb-d44dd30ca3f6)

2023-11-20 17:12 UTC, vijay-stephen commented on example/main.tf
> +    Repo         = "github.com/sourcefuse/refarch-devops-infra"
its done

2023-11-20 17:13 UTC, tsaucier-sf requested changes

2023-11-20 17:13 UTC, tsaucier-sf commented on sns.tf
> +    Id      = "key-policy-1",
We should probably omit this if we can

2023-11-20 17:13 UTC, tsaucier-sf commented on example/data.tf
> +  name = "/${var.namespace}/poc/guard-duty/opsgenie/api-key"
change poc --> `${var.environment}`

2023-11-20 17:13 UTC, tsaucier-sf commented on example/data.tf
> +  name = "/${var.namespace}/poc/security-hub/opsgenie/api-key"
change poc --> `${var.environment}`

2023-11-20 17:13 UTC, tsaucier-sf commented on example/data.tf
> +  name = "/${var.namespace}/poc/aws-config/opsgenie/api-key"
change poc --> `${var.environment}`

2023-11-20 17:46 UTC, vijay-stephen commented on main.tf
> +  create_sns_topic  = true
Problem is , `create_sns_topic` doesn't work for guard duty, Should I still create a variable ?

2023-11-20 17:46 UTC, vijay-stephen commented on main.tf
> +  create_sns_topic      = false
Problem is , `create_sns_topic` doesn't work for guard duty, Should I still create a variable ?

2023-11-20 17:51 UTC, vijay-stephen commented on sns.tf
> +    Id      = "key-policy-1",
you mean remove the `Id` ?

2023-11-20 17:52 UTC, vijay-stephen commented on main.tf
create_sns_topic doesn't work for guard duty, thats why create_sns_topic is not exposed.

2023-11-20 17:52 UTC, tsaucier-sf commented on sns.tf
> +    Id      = "key-policy-1",
Yes

2023-11-20 22:57 UTC, tsaucier-sf approved these changes

2023-11-21 13:51 UTC, vijay-stephen commented on main.tf
Removed count and used `enabled`

2023-11-21 13:54 UTC, merged